name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Set up Firebase credentials
      run: |
        mkdir -p $HOME/.firebase  # Create the directory if it doesn't exist
        echo "${{ secrets.FIREBASE_CREDENTIALS_JSON }}" > $HOME/.firebase/credentials.json

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase
      run: firebase deploy --token ${{ secrets.FIREBASE_AUTH_TOKEN }}
