name: Firebase Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Firebase credentials
        run: |
          echo "${{ secrets.FIREBASE_CREDENTIALS_JSON }}" > $HOME/.firebase/credentials.json

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to Firebase
        run: |
          firebase deploy --token "$(cat $HOME/.firebase/credentials.json)"
